import 'package:admin_dashboard/src/routes/routes.gr.dart';
import 'package:auto_route/auto_route.dart';

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends $AppRouter {
  @override
  RouteType get defaultRouteType => RouteType.material();
  @override
  final List<AutoRoute> routes = [
    AutoRoute(path: '/', page: MenuBar.page, children: [
      RedirectRoute(path: '', redirectTo: 'dashboard'),
      AutoRoute(
        path: 'dashboard',
        page: Dashboard.page,
      ),
      AutoRoute(path: 'calendar', page: Calendar.page),
      AutoRoute(path: 'map', page: GoogleMaps.page),
      AutoRoute(path: 'toast', page: Toast.page),
      AutoRoute(path: 'button-element', page: Button.page),
      AutoRoute(path: 'rating-bar', page: Rating.page),
      AutoRoute(path: 'badge', page: Badge.page),
      AutoRoute(path: 'alert-dialog', page: AlertDialogBox.page),
      AutoRoute(path: 'modal', page: Modal.page),
      AutoRoute(path: 'loaders', page: Loaders.page),
      AutoRoute(path: 'tabs', page: TabScreen.page),
      AutoRoute(path: 'basic-action-email', page: BasicEmail.page),
      AutoRoute(path: 'alert-email', page: AlertEmail.page),
      AutoRoute(path: 'billing-email', page: BillingEmail.page),
      AutoRoute(path: 'morris-chart', page: MorrisChart.page),
      AutoRoute(path: 'chartist-chart', page: ChartListChart.page),
      AutoRoute(path: 'chartjs-chart', page: ChartJsChart.page),
      AutoRoute(path: 'basic-table', page: BasicTable.page),
      AutoRoute(path: 'data-table', page: Datatable.page),
      AutoRoute(path: 'responsive-table', page: ResponsiveTable.page),
      AutoRoute(path: 'editable-table', page: EditableTable.page),
      AutoRoute(path: 'timeline', page: TimelineScreen.page),
      AutoRoute(path: 'pricing', page: Pricing.page),
      AutoRoute(path: 'card', page: DirectoryRoute.page),
      AutoRoute(path: 'faqs', page: FAQs.page),
      AutoRoute(path: 'invoice', page: Invoice.page),
      AutoRoute(path: 'gallery', page: Gallery.page),
      AutoRoute(path: 'carousel-slider', page: Carousel.page),
      AutoRoute(path: 'elements', page: ElementsForm.page),
      AutoRoute(path: 'validation', page: ValidationForm.page),
      AutoRoute(path: 'dropzone', page: FileUploadForm.page),
      AutoRoute(path: 'repeater', page: RepeaterForm.page),
      AutoRoute(path: 'mask', page: MaskForm.page),
      AutoRoute(path: 'wizard', page: WizardForm.page),
      AutoRoute(path: 'video-player', page: VideoScreen.page),
      AutoRoute(path: 'user-profile', page: UserProfile.page),
      AutoRoute(path: 'usuarios', page: UsersViewTest.page),
      AutoRoute(path: 'categorias', page: CategoriesViewTest.page),
      AutoRoute(path: 'productos', page: ProductsViewTest.page),
      AutoRoute(path: 'traspasos', page: TransfersViewTest.page),
      AutoRoute(path: 'movimientos', page: MovementsViewTest.page),
      AutoRoute(path: 'stocks', page: StocksViewTest.page),
      AutoRoute(path: 'verificaciones', page: VerificationsViewTest.page),
      AutoRoute(path: 'traspasos-crear', page: TransferViewTest.page),
      AutoRoute(path: 'cotizaciones', page: ListingsViewTest.page),
      AutoRoute(path: 'cotizaciones-crear', page: ListingViewTest.page),
      AutoRoute(path: 'ventas', page: SalesViewTest.page),
      AutoRoute(path: 'ventas-ver', page: SaleViewTest.page),
    ]),
    AutoRoute(path: '/login-one', page: LoginOne.page),
    AutoRoute(path: '/login-two', page: LoginTwo.page),
    AutoRoute(path: '/register-one', page: RegisterOne.page),
    AutoRoute(path: '/register-two', page: RegisterTwo.page),
    AutoRoute(path: '/recover-password-one', page: RecoverPasswordOne.page),
    AutoRoute(path: '/recover-password-two', page: RecoverPasswordTwo.page),
    AutoRoute(path: '/lock-screen-one', page: LockScreenOne.page),
    AutoRoute(path: '/lock-screen-two', page: LockScreenTwo.page),
    AutoRoute(path: '/error-404', page: Error404.page),
    AutoRoute(path: '/error-500', page: Error500.page),
    AutoRoute(path: '/coming-soon', page: ComingSoon.page),
    AutoRoute(path: '/maintenance', page: Maintenance.page),
  ];
}
